### ISSUE TITLE
Mounting AWS S3 as the second tier.

### ISSUE THREAD

**Issue by chadbrewbaker** [versity/scoutfs-kmod-dev#47]
AWS S3 supports HTTP range queries, making files stored as binary blobs in SQLite efficient for reads, https://github.com/dacort/athena-sqlite/blob/master/lambda-function/vfs.py

What do you need to implement a scoutfs a second tier device?  Ideally, also throwing in some zstd dictionary compression to lower secondary network bandwidth/storage size.

**Comment by benmcclelland** [comment]
@chadbrewbaker the scoutfs filesystem has moved to a new repo that combines userspace, kernel modules, and some tests.  Here is the new location: https://github.com/versity/scoutfs

In the tests repo, there are some examples of making copies of file data somewhere else (archive), releasing the datablocks in the filesystem (release), and then restoring the data blocks back from where they were stored (stage).  See: https://github.com/versity/scoutfs/blob/main/tests/tests/simple-staging.sh

Where the data goes, how to find it, if it gets compressed, deduped, etc is all up to the userspace component that is using these archive/release/stage filesystem interfaces.

**Comment by zabbo** [comment]
Can you expand a bit on what would be stored on the second tier device?   If you're talking about archived file data that has nothing to do with the scoutfs kernel file system.  Maybe you're talking about putting the scoutfs devices in s3?   That'd be a different beast entirely, and would have to go through some kind of kernel block device that worked with s3.
